version: "3.9"
services:
  vote:
    image: docker.dc.afranet.co/dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - frontend
    deploy:
      replicas: 2

  result:
    image: docker.dc.afranet.co/dockersamples/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend

  worker:
    image: docker.dc.afranet.co/dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2

networks:
  frontend:
    attachable: true
  backend:
    attachable: true

